## EDA1: Análisis Exploratorio de los datasets .csv disponibles en los directorios: store_zara_data, women_zara_csvs, men_zara_csvs

In [9]:
import pandas as pd
import os
pd.set_option('display.max_colwidth', None)

* El método `os.listdir()` de python permite obtener la **lista** de todos los archivos o directorios del directorio especificado.

In [10]:
## Ejemplo: Mostrar el contenido del directorio data
os.listdir('../data')

['img_eml', 'men_zara_csvs', 'store_zara_data', 'women_zara_csvs']

In [11]:
## Ejemplo: Mostrar los ficheros en del directorio women_zara_csvs de data
print(type(os.listdir("../data/women_zara_csvs/")))
print(os.listdir("../data/women_zara_csvs/"))

<class 'list'>
['ACCESSORIES_JEWELLERY.csv', 'BAGS.csv', 'BASICS.csv', 'BEAUTY.csv', 'BLAZERS.csv', 'CO-ORD SETS.csv', 'DRESSES_JUMPSUITS.csv', 'JACKETS.csv', 'JEANS.csv', 'KNITWEAR.csv', 'LOUNGEWEARNEW.csv', 'PERFUMESNEW.csv', 'SHIRTS.csv', 'SHOES.csv', 'SHORTS_SKORTS.csv', 'SKIRTS.csv', 'SPECIAL PRICES.csv', 'T-SHIRTS_SWEATSHIRTS.csv', 'TOPS_BODYSUITS.csv', 'TROUSERS.csv', 'WAISTCOATS_GILETS.csv', 'WORKWEARNEW.csv']

In [12]:
# Ruta del directorio
directorio = '../data/store_zara_data'

# Obtener la lista de archivos en el directorio que terminen con .csv
archivos = [f for f in os.listdir(directorio) if f.endswith('.csv')]

print(archivos)

['store_zara.csv']

In [13]:
def get_info_datasets(path:str):
    """ Devuelve un DataFrame con la información de los csvs contenido en cada direcctorio """
    #csvs = os.listdir(path)
    csvs = [f for f in os.listdir(path) if f.endswith('.csv')]
    csvs_content = []

    for csv in csvs:
        df = pd.read_csv(path +'/'+ csv, sep=",")
        csvs_content.append([csv, df.shape[0], df.shape[1], df.columns])

    df_csvs = pd.DataFrame(csvs_content, columns=["csv", "filas", "columnas", "nombres_columnas"])
    df = df_csvs.sort_values("filas", ascending=False)
    return df

In [14]:
store_zara = get_info_datasets("../data/store_zara_data")
store_zara

,csv,filas,columnas,nombres_columnas
0,store_zara.csv,3129,13,"Index(['brand', 'url', 'sku', 'name', 'description', 'price', 'currency', 'images', 'scraped_at', 'terms', 'section', 'error', 'image_downloads'], dtype='object')"

In [15]:
women = get_info_datasets("../data/women_zara_csvs")
women

,csv,filas,columnas,nombres_columnas
6,DRESSES_JUMPSUITS.csv,643,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
13,SHOES.csv,284,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
9,KNITWEAR.csv,228,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
12,SHIRTS.csv,210,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
21,WORKWEARNEW.csv,177,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
0,ACCESSORIES_JEWELLERY.csv,156,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
7,JACKETS.csv,113,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
1,BAGS.csv,110,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
18,TOPS_BODYSUITS.csv,108,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
19,TROUSERS.csv,107,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
16,SPECIAL PRICES.csv,100,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
11,PERFUMESNEW.csv,68,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
4,BLAZERS.csv,67,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
20,WAISTCOATS_GILETS.csv,66,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
15,SKIRTS.csv,59,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
14,SHORTS_SKORTS.csv,57,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
17,T-SHIRTS_SWEATSHIRTS.csv,42,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
5,CO-ORD SETS.csv,34,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
2,BASICS.csv,24,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
10,LOUNGEWEARNEW.csv,21,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
3,BEAUTY.csv,18,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"
8,JEANS.csv,15,6,"Index(['Unnamed: 0', 'Product_Name', 'Link', 'Product_Image', 'Price', 'Details'], dtype='object')"

In [16]:
men = get_info_datasets("../data/men_zara_csvs")
men

,csv,filas,columnas,nombres_columnas
11,SHIRTS.csv,175,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
12,SHOES.csv,166,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
0,ACCESSORIES.csv,148,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
17,T-SHIRTS.csv,144,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
1,BAGS_BACKPACKS.csv,139,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
18,TROUSERS.csv,119,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
13,SHORTS.csv,86,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
15,SWEATERS_CARDIGANS.csv,82,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
5,JACKETS.csv,66,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
19,ZARA ATHLETICZ.csv,53,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
10,POLO SHIRTS.csv,47,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
7,LINEN.csv,46,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
9,PERFUMES.csv,44,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
16,SWIMWEAR.csv,39,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
4,HOODIES_SWEATSHIRTS.csv,32,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
8,OVERSHIRTS.csv,25,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
3,BLAZERS.csv,22,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
2,BEAUTY.csv,17,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
6,JEANS.csv,15,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
20,ZARA ORIGINS.csv,12,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"
14,SUITS.csv,1,6,"Index(['Unnamed: 0', 'product_name', 'link', ' product_images', 'price', 'details'], dtype='object')"